server:
  port: 80

eureka:
  client:
    service-url:
      #集群指向其它eureka
      #defaultZone: http://eureka7002.com:7002/eureka/
      #单机就是7001自己
      #        defaultZone: http://eureka7001.com:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控什么接口
    com.lrz.springcloud.service.PaymentFeignService: debug